#include <stdio.h>
#include "version_info.h"  /* auto-generated by Makefile on every build */

void print_build_info(void)
{
    printf("[ak_rtsp] build #%d | %s | git:%s\n",
           BUILD_NUMBER, BUILD_TIMESTAMP, GIT_HASH);
}
